### ISSUE TITLE
How much should global variables cost?

### ISSUE THREAD

**Issue by carycode** [r00k/blog#4]
I think your blog post
"How much should global variables cost?"
is great except for one thing:
the body of the post never actually mentions the "global variables" mentioned in the title.

I bet I'm not the only person wondering if maybe something got accidentally chopped off and lost in the series of tubes and processors between your brain and my eyeballs.
Maybe the you deliberately left out "global variables" for some reason that maybe to you is obvious, but the implication you alluded to is not so obvious to those of us who cannot telepathically read your mind.

Perhaps you could duplicate the "Use of local variables" section, creating a "Use of global variables" section with a (much higher) fee and a pithy summary.

Or perhaps it would be better to explicitly state at the bottom of the post something like
"I deliberately did not specify a fee for global variables, because rather than try to eliminate global variables at all costs, I want to remind you to think about all the other things you could do to make your code more awesome."

"How much should global variables cost?"
http://www.benorenstein.com/blog/how-much-should-global-variables-cost/
(which I found via
http://bluebones.net/2013/08/how-much-should-global-variables-cost/
via ... via
http://en.wikipedia.org/wiki/Lightweight_markup_language
)

**Comment by r00k** [comment]
Hah, good point! I somehow never caught that.

I think I'll probably add a section on global variables.

Thanks for the issue.

**Comment by r00k** [comment]
Closing this for now. Not sure I'll get to it, honestly :).
